### PR TITLE
Strip decorators from enum (#60)

### PR DESCRIPTION
**Pull request by jonathanp**

### CODE REVIEW

**Comment by jonathanp** [comment]
Me and @AdnanDervisevic discussed that a bit and we thought this solution was more readable, but sure it could have been done with one large regex instead.

**Comment by ffMathy** [comment]
I would personally prefer one large regex. But what we could consider doing is splitting it up into constants that denote the part that they are from.

**Comment by jonathanp** [comment]
Regexes isn't one of my strongest skills, could you assist us with that? Or maybe use this solution for now and refactor into a more elegant solution later?

**Comment by ffMathy** [comment]
Me neither. I usually use regex101.com where you can enter the whole regex as a string and then some results it should match, and then go from there. 

It's usually a lot easier. I don't have a lot of time until next week, so it would be great if you could give it a shot first.

**Comment by jonathanp** [comment]
I've given it a shot now, and I can't manage to do all the parsing in the single regex. Would appreciate if you can take a look at it when you have time next week, or merge this solution as an interim solution.

**Comment by AdnanDervisevic** [comment]
Just wanted to chime in and say that I spent quite a bit of time on this yesterday and couldn't actually get a regex that worked for every situation that we need to be able to handle with this case :(

**Comment by ffMathy** [comment]
You guys are right. I can fix it later. Important thing is that there are tests for it now.

**Pull request merged**
