### PR TITLE
Add support for ignoring methods

### PR DESCRIPTION
**Pull request by jonathanp**
Issue #45

### CODE REVIEW

**Comment by ffMathy** [comment]
Nice, but where is the test for readonly?

**Comment by ffMathy** [comment]
And also instead of "ignoreReadOnly" can you call it "removeReadOnly"?

**Comment by Evertras** [comment]
Might even suggest something like `stripReadOnly` for clarity.

**Comment by ffMathy** [comment]
Ah yes even better!

**Comment by jonathanp** [comment]
This PR only contains functionality for ignoring methods. The `readonly` stuff was merged in #48. I agree that `stripReadOnly` would be a better name, but maybe rename it in another commit/PR?

**Comment by ffMathy** [comment]
I think it should be renamed now, because it hasn't been out for very long, and now is our chance to do it.

**Comment by jonathanp** [comment]
Sure you can go ahead and rename it

**Comment by ffMathy** [comment]
I would, but I don't have a lot of time at the moment, and I really think it should be done as part of this pull request. If you already have this project set up on your machine, isn't it just a search and replace?

Then everyone is happy, and you get your `ignoreMethods` property.

**Comment by ffMathy** [comment]
Contextually it doesn't belong in the same pull request, but it is a lot more convenient, and I thought it would be easy for you to change it in the same pull request?

**Comment by jonathanp** [comment]
Ok the option is renamed in #50 now. Please go ahead and merge this PR :)

**Comment by ffMathy** [comment]
It has conflicts.

**Comment by jonathanp** [comment]
Conflicts resolved

**Comment by jonathanp** [comment]
Thanks for the merge, don't forget to bump the version and publish it to npm please.

**Comment by ffMathy** [comment]
You're welcome, and thanks for the rename. Will do. @Evertras how is that done? Can you give me access to the NPM repo?

@jonathanp as a temporary workaround you can refer to the GitHub repository directly in your `package.json` file.

**Comment by Evertras** [comment]
Do you have a registered account on [NPM](https://www.npmjs.com)?

**Comment by ffMathy** [comment]
Now I do. The account name is ffMathy.

**Comment by Evertras** [comment]
I've added you as an owner to both packages.  You should be able to bump the version number in `package.json` and do `npm publish`.  You'll have to `npm login` with ffMathy first.  Let me know if it works.

Also, for versioning, I've been trying to go Major Minor Revision as is popular, with Minor being an actual change in functionality or tweaking of options (including the latest rename of an option), with Revision being bug fixes or improvements that don't affect functionality.  Major would be for a total rewrite at this point.

**Comment by Evertras** [comment]
Also, make sure to update the dependency version in `gulp-typescript-cs-poco`.  I've kept them in lockstep so far.  That's worked nicely.

**Comment by ffMathy** [comment]
Will do. And what about your Jenkins setup, can I get access to that as well and can you make it work for my repo? 

I am considering making Jenkins do a publish automatically when changes are pushed to master.

**Comment by Evertras** [comment]
It's just Travis.  It's actually already trying to work for the moved repo: https://travis-ci.org/ffMathy/typescript-cs-poco

You'll have to sign in there and futz with it, it's been so long since I've touched it, but I remember it being pretty straightforward.  You'll probably have to update the README to point to the correct URL if nothing else.

**Pull request merged**
